---
driver:
  name: vagrant
  customize:
    memory: 4192
 
provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

# provision Ambari to use IP specified in network clause 
platforms:
  - name: precise64
    run_list:
       - recipe[ambari-chef::default]
    driver:
      box: precise64
      box_url: precise-server-cloudimg-amd64-vagrant-disk1.box
      network:
      - [ "private_network" , { ip : "192.168.101.101" } ]	

suites:
  - name: default
    attributes:
