---
driver:
  name: vagrant
  customize:
    memory: 4192

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
       - recipe[java::oracle]
       - recipe[ambari-chef::default]
    driver:
      box: bento/ubuntu-14.04
      network:
      - [ "private_network" , { ip : "192.168.33.7" } ]	
suites:
  - name: default
    attributes:
